name: Update website files

on: 
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' 
        S3_BUCKET: 'website-bucket-welcomed-bat'  
        S3_KEY: 'index.html'  
      run: |
        aws s3 cp index.html s3://$S3_BUCKET/$S3_KEY
